# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f106d533da300f0ca3d0b85643a2034e97d98d287a8c9b12df9650ba5c5bf2a7749ab21d38981f4e6240599aec6d14a484c5179a500bef0663c6e238f1a5d35a

test:
  secret_key_base: a06a8986685916728964def27c4620d2e3ff57e05172aaa40e0998eed639880000fe803250ea24ee39e95aaaefc064e7a8a898923a03536e0590935ad14196a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
